### ISSUE TITLE
Hi DacoTaco

### ISSUE THREAD

**Issue by Mad31fish** [DacoTaco/TSS#3]
Is there anyway I can use the Wiimmfi disc channel patcher without the need of priiloader menu booting up? When I hold reset I get the priiloader menu on my Wii. I want this gone. Is there anyway to use the wiimmfi disc channel patcher without the prilloader menu booting up? Does forcing priiloader to start the Wii menu do the trick? I know changing the Wii menu will not do the trick because even when it's found it will not connect to wiimffi. Is there anyway to do this? Thanks so much for your help.

**Comment by DacoTaco** [comment]
Hi, 
first of all, this repository is not priiloader related. if you want to talk more about this, please make a new issue @ the priiloader repo ( https://github.com/DacoTaco/priiloader/issues ).

I also have a hard time understanding what you are wanting to do. i understand you want priiloader to apply the disc patches for wiimmfi when launching system menu? there is a hack for that. i'm not sure why you are constantly going into the priiloader menu? you just need to enable the hack ..

**Comment by Mad31fish** [comment]
Hi Dacotaco. 
Thanks so much for getting back to me. This message is from my

**Comment by Mad31fish** [comment]
This message is from my son whose 14 and has autism. He is a huge fan of yours but is obsessing over the menu popping up when he holds down the reset button.I wish I knew how better to state his problem but this is well out of my league. I'll try to get him to simplify what he is trying to do. Thanks so much for responding.

**Comment by DacoTaco** [comment]
no problem, if any problems come up feel free to poke me.
is there any reasons why he is holding the reset button? can he explain it in some way?

**Comment by Mad31fish** [comment]
Thank you. My son is trying to keep the wiimmfi patcher for Wii disc channel. He has heard there is a way to remove priiloader and keep the wiimmfi disc channel patcher. When he installs it it attempts to delete leftover files and system menu hacks is one of them. I know that changing the Wii menu doesn't do the trick cause even when the hacks found it can't connect to wiimmfi. I also heard there is itching game disc to wiimmfi. Can you make something that allows people to use priiloader hacks enabled without priiloader installed. When he presses reset it reloads the priiloader menu and he wants to get rid of that and keep the wiimmfi disc channel patcher. 
Ok. That's what I got from him. 
I have to be honest if he hears from you that there is no way to do this than it might stop him from obsessing about it. I can't thank you enough. We are very proud of him for figuring this all out on his own and is now able to play online with the Wii world again. You are a rock star. Thanks for any advice. And I'm so sorry this is so confusing.

**Comment by DacoTaco** [comment]
ah i understand. 
im not part of the wiimmfi team, and they might have a better understanding of the options to make the disc patching permanent.
However, from a Priiloader & System menu standpoint i can only say that removing priiloader would have to be done manually, or through a system menu update (but if the wii is on version 4.3 you will not be installing any updates that overwrite priiloader). and there are even priiloader hacks that stop update installation :)
I suspect/assume your son must have heard about updates overwriting it, which would remove priiloader applying the disc patching hack.

The disc patching is also not a hack like the others, as it doesn't just alter some bits and pieces of code in system menu, but actually adds a lot of code. Im just guessing , but i think this is why normal (permanent) patchers can't do it out of the box.
Im sure there is a way to put the disc patching into system menu without priiloader (adding the extra code to system menu + altering the existing code) but its dangerous to install and would mean that any wiimmfi updates (like the recent one) would require you to do the same thing all over again.

PS : i don't know how bad the autism is, but if you are a parent and are proud of your son, then good job from me to him for figuring out to go to github and posting an issue requesting help (despite it being on the repo of my terrible terrible thesis hehe). that is a good skill that he applied !

**Comment by Mad31fish** [comment]
Thanks so much. I think we may have solved the problem. Only time we'll tell. Thanks a million!

**Comment by Mad31fish** [comment]
Hi DacoTaco. I'm trying one last attempt on my Wii. I know I can't remove priiloader and keep wiimmfi disc channel patcher but maybe forcing priiloader to start the Wii with a magic word like abra is the trick because it's not removing priiloader it's just forcing you to restart the Wii menu. Here is some evidence I found that I think it will work. One-when I set my auto boot to home brew channel and install the system menu wad the next time I turned off my Wii and turned it back on it would not load homebrew channel but load system menu. So is it possible to use a magic word like abra to circumvent the priiloader menu when I hold the reset button down. More evidence- when it's set to boot with installed file on your Wii even adding the magic word on your Wii would still start installed file. Can I do this without locking out my Wii?
Whatever you tell me to do I will do. If it can't be done than I will move on. Thanks so much for being the best helper I could find. 
Lucas

**Comment by Mad31fish** [comment]
My problem has been solved. Thanks DacoTaco!!you're the best!!

**Comment by DacoTaco** [comment]
Hi!

sorry it took so long to reply. I've been very busy with personal things and was unable to reply. Did i understand it correctly that you want priiloader to boot system menu on startup, and having the magic words have that function?
because you can set priiloader to auto launch system menu on startup, or on restart. 
i assume you got it set up to launch something else on startup, and in that case the other app would need to control Priiloader's behavior through the magic word.

how did you fix your problem?

**Comment by Mad31fish** [comment]
Well, there was a new wiimmfi patcher for disc channel. It didn't require anything but I had to change the dns. I think my problem is finally solved. Thanks so much for getting back to me. I appreciate all of your guidance.
